In [5]:
cd ../edit_distance

/home/sean/Code/d3m-sequences/edit_distance


In [6]:
import edit_norm

In [7]:
import numpy as np

In [8]:
import pandas as pd

In [9]:
df = edit_norm.measures_all_probs_categories()

lp_norm: No performer had more than one pipeline.


In [10]:
df.head()

performer     l1         l2  linf  max_score  count  prob_num  \
0       mit  144.0  24.000000   4.0     0.2711     20         0   
1       cmu   55.0   7.416198   1.0     0.8199     11         0   
2       ucb   12.0   7.071068   5.0     0.2711      3         0   
3       isi    6.0   6.000000   6.0     0.3373      2         0   
4      tamu    1.0   1.000000   1.0     0.4921      2         0   

                      prob_name                         keywords  \
0  124_174_cifar10_MIN_METADATA  classification,multiClass,image   
1  124_174_cifar10_MIN_METADATA  classification,multiClass,image   
2  124_174_cifar10_MIN_METADATA  classification,multiClass,image   
3  124_174_cifar10_MIN_METADATA  classification,multiClass,image   
4  124_174_cifar10_MIN_METADATA  classification,multiClass,image   

                    category  ranking   best  l1_zscore  l2_zscore  \
0  multiclass_classification      4.0  False   1.868432   1.910640   
1  multiclass_classification      1.0   True   0.212153  -0.215552   
2  multiclass_classification      4.0  False  -0.588072  -0.259801   
3  multiclass_classification      3.0  False  -0.699731  -0.397121   
4  multiclass_classification      2.0  False  -0.792781  -1.038166   

   linf_zscore  max_score_zscore  count_zscore  
0     0.291386         -0.807013      1.756437  
1    -1.165543          1.841843      0.481604  
2     0.777029         -0.807013     -0.651582  
3     1.262672         -0.487490     -0.793230  
4    -1.165543          0.259673     -0.793230

In [12]:
df.columns

Index(['performer', 'l1', 'l2', 'linf', 'max_score', 'count', 'prob_num',
       'prob_name', 'keywords', 'category', 'ranking', 'best', 'l1_zscore',
       'l2_zscore', 'linf_zscore', 'max_score_zscore', 'count_zscore'],
      dtype='object')

In [13]:
dg = df.groupby(['prob_name'])

The below shows the standard deviations of all variables (predictors and response)

In [75]:
dgstd = dg.std()[['max_score', 'max_score_zscore', 'l1', 'linf', 'count']]

In [76]:
dgstd

max_score  \
prob_name                                                          
124_174_cifar10_MIN_METADATA                        2.316386e-01   
124_188_usps_MIN_METADATA                           3.433531e-01   
124_214_coil20_MIN_METADATA                         4.336812e-01   
124_95_uc_merced_land_use_MIN_METADATA              4.076517e-01   
1491_one_hundred_plants_margin_MIN_METADATA         5.273332e-02   
1567_poker_hand_MIN_METADATA                        2.290259e-01   
185_baseball_MIN_METADATA                           5.050633e-02   
196_autoMpg_MIN_METADATA                            2.043031e+00   
22_handgeometry_MIN_METADATA                        8.394656e-02   
26_radon_seed_MIN_METADATA                          4.960364e-03   
27_wordLevels_MIN_METADATA                          1.787334e-02   
299_libras_move_MIN_METADATA                        2.900026e-01   
30_personae_MIN_METADATA                            3.106972e-02   
313_spectrometer_MIN_METADATA                       1.935433e-01   
31_urbansound_MIN_METADATA                          1.578126e-01   
32_fma_MIN_METADATA                                 5.018675e-02   
32_wikiqa_MIN_METADATA                              1.706845e-01   
38_sick_MIN_METADATA                                1.785764e-02   
4550_MiceProtein_MIN_METADATA                       0.000000e+00   
49_facebook_MIN_METADATA                            4.099099e-03   
534_cps_85_wages_MIN_METADATA                       2.973055e+00   
56_sunspots_MIN_METADATA                            9.807220e+00   
56_sunspots_monthly_MIN_METADATA                    8.447168e+00   
57_hypothyroid_MIN_METADATA                         1.633900e-02   
59_LP_karate_MIN_METADATA                           7.033191e-03   
59_umls_MIN_METADATA                                7.087113e-02   
60_jester_MIN_METADATA                              5.654322e-01   
66_chlorineConcentration_MIN_METADATA               2.516078e-01   
6_70_com_amazon_MIN_METADATA                        4.876566e-02   
6_86_com_DBLP_MIN_METADATA                          1.046914e-01   
...                                                          ...   
LL1_TXT_CLS_3746_newsgroup_MIN_METADATA             6.876460e-02   
LL1_TXT_CLS_airline_opinion_MIN_METADATA            3.697005e-02   
LL1_TXT_CLS_apple_products_sentiment_MIN_METADATA   3.043577e-02   
LL1_VID_UCF11_MIN_METADATA                          3.988254e-02   
LL1_VTXC_1343_cora_MIN_METADATA                     1.717505e-01   
LL1_VTXC_1369_synthetic_MIN_METADATA                2.507611e-01   
LL1_crime_chicago_MIN_METADATA                      0.000000e+00   
LL1_net_nomination_seed_MIN_METADATA                2.361746e-01   
LL1_retail_sales_total_MIN_METADATA                 3.985144e+02   
LL1_terra_canopy_height_long_form_s4_100_MIN_ME...  9.153344e-01   
LL1_terra_canopy_height_long_form_s4_70_MIN_MET...  4.649457e+02   
LL1_terra_canopy_height_long_form_s4_80_MIN_MET...  1.474143e+01   
LL1_terra_canopy_height_long_form_s4_90_MIN_MET...  6.218871e+00   
LL1_terra_leaf_angle_mean_long_form_s4_MIN_META...  8.205414e-04   
SEMI_1044_eye_movements_MIN_METADATA                2.399515e-01   
SEMI_1459_artificial_characters_MIN_METADATA        2.914176e-01   
SEMI_155_pokerhand_MIN_METADATA                     1.527949e-01   
kaggle_music_hackathon_MIN_METADATA                 1.785919e+00   
loan_status_MIN_METADATA                            4.194389e-02   
political_instability_MIN_METADATA                  3.406896e-02   
uu10_posts_3_MIN_METADATA                           1.461861e-01   
uu1_datasmash_MIN_METADATA                          3.722369e-01   
uu2_gp_hyperparameter_estimation_MIN_METADATA       3.774310e-07   
uu4_SPECT_MIN_METADATA                              1.423178e-02   
uu5_heartstatlog_MIN_METADATA                       3.376146e-02   
uu6_hepatitis_MIN_METADATA                          1.452472e-01   
uu7_pima_diabetes_MIN_METADATA             

These below have all max_scores equal (standard deviation equals zero, all scores ties)

In [78]:
dgstd[dgstd['max_score']==0]

max_score  max_score_zscore          l1  \
prob_name                                                                 
4550_MiceProtein_MIN_METADATA         0.0               NaN  495.454625   
LL1_crime_chicago_MIN_METADATA        0.0               NaN  519.590897   

                                    linf     count  
prob_name                                           
4550_MiceProtein_MIN_METADATA   6.156684  6.347103  
LL1_crime_chicago_MIN_METADATA  2.732520  7.386925

We drop them because they doesn't make sense to include collections where all scores are equal.

In [79]:
gstd = dgstd[dgstd['max_score']!=0]

In [82]:
np.percentile(gstd['max_score_zscore'],[0,25,50,75,100])

array([1.06066017, 1.06904497, 1.08012345, 1.08012345, 1.11803399])

In [81]:
np.percentile(gstd['l1'],[0,25,50,75,100])

array([ 24.70627451, 170.84601158, 294.3607479 , 375.38633333,
       531.60684654])

In [84]:
np.percentile(gstd['linf'],[0,25,50,75,100])

array([2.12132034, 3.46211009, 3.81694217, 4.5614847 , 7.96308447])

In [85]:
np.percentile(gstd['count'],[0,25,50,75,100])

array([1.41421356, 5.72582588, 6.99663563, 7.589856  , 8.6890736 ])

In [86]:
l1_std_ratio = gstd['max_score_zscore']/gstd['l1']

In [87]:
np.percentile(l1_std_ratio,[0,25,50,75,100])

array([0.00201097, 0.00287407, 0.00367774, 0.00625897, 0.04433874])

In [88]:
np.percentile(l1_std_ratio,[95,96,97,98,99,100])

array([0.01411363, 0.01623121, 0.01894673, 0.02431259, 0.04128912,
       0.04433874])

In [89]:
l1_std_ratio.sort_values().tail(5)

prob_name
LL1_FISH_MIN_METADATA                    0.014362
124_174_cifar10_MIN_METADATA             0.018610
LL1_VID_UCF11_MIN_METADATA               0.019631
uu_101_object_categories_MIN_METADATA    0.040912
124_188_usps_MIN_METADATA                0.044339
dtype: float64

'LL0_207_autoPrice_MIN_METADATA' has a very large standard deviation for max_score (because scores were very large).  This came up before we were using max_score_zscore, as above.

In [90]:
df[df['prob_name']=='LL0_207_autoPrice_MIN_METADATA']

performer     l1         l2  linf     max_score  count  prob_num  \
228       isi  473.0  53.150729  10.0 -3.794082e+06     16        32   
229       sri  215.0  20.808652   3.0 -4.194508e+06     19        32   
230      tamu  190.0  13.784049   1.0 -5.193412e+06     20        32   
231       mit   27.0   9.110434   4.0 -9.222177e+06      5        32   
232       cmu   17.0   8.306624   5.0 -3.905764e+06      4        32   

                          prob_name                       keywords  \
228  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
229  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
230  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
231  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
232  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   

       category  ranking   best  l1_zscore  l2_zscore  linf_zscore  \
228  regression      1.0   True   1.743145   1.927558     1.796013   
229  regression      3.0  False   0.184824  -0.013410    -0.532152   
230  regression      4.0  False   0.033824  -0.434982    -1.197342   
231  regression      5.0  False  -0.950697  -0.715463    -0.199557   
232  regression      2.0  False  -1.011097  -0.763703     0.133038   

     max_score_zscore  count_zscore  
228          0.719330      0.463039  
229          0.523107      0.897139  
230          0.033605      1.041838  
231         -1.940644     -1.128658  
232          0.664602     -1.273358

In [91]:
dfstd = pd.DataFrame(gstd).reset_index()

In [92]:
dfstd[ggstd['prob_name']=='LL0_207_autoPrice_MIN_METADATA']

prob_name     max_score  max_score_zscore  \
31  LL0_207_autoPrice_MIN_METADATA  2.281524e+06          1.118034   

            l1      linf     count  
31  185.104835  3.361547  7.726578

In [93]:
df[df['prob_name']=='LL0_207_autoPrice_MIN_METADATA']

performer     l1         l2  linf     max_score  count  prob_num  \
228       isi  473.0  53.150729  10.0 -3.794082e+06     16        32   
229       sri  215.0  20.808652   3.0 -4.194508e+06     19        32   
230      tamu  190.0  13.784049   1.0 -5.193412e+06     20        32   
231       mit   27.0   9.110434   4.0 -9.222177e+06      5        32   
232       cmu   17.0   8.306624   5.0 -3.905764e+06      4        32   

                          prob_name                       keywords  \
228  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
229  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
230  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
231  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   
232  LL0_207_autoPrice_MIN_METADATA  regression,univariate,tabular   

       category  ranking   best  l1_zscore  l2_zscore  linf_zscore  \
228  regression      1.0   True   1.743145   1.927558     1.796013   
229  regression      3.0  False   0.184824  -0.013410    -0.532152   
230  regression      4.0  False   0.033824  -0.434982    -1.197342   
231  regression      5.0  False  -0.950697  -0.715463    -0.199557   
232  regression      2.0  False  -1.011097  -0.763703     0.133038   

     max_score_zscore  count_zscore  
228          0.719330      0.463039  
229          0.523107      0.897139  
230          0.033605      1.041838  
231         -1.940644     -1.128658  
232          0.664602     -1.273358

In [95]:
0.2/dgstd['l1']

prob_name
124_174_cifar10_MIN_METADATA                             0.003329
124_188_usps_MIN_METADATA                                0.008095
124_214_coil20_MIN_METADATA                              0.000742
124_95_uc_merced_land_use_MIN_METADATA                   0.000698
1491_one_hundred_plants_margin_MIN_METADATA              0.000478
1567_poker_hand_MIN_METADATA                             0.000523
185_baseball_MIN_METADATA                                0.000534
196_autoMpg_MIN_METADATA                                 0.000513
22_handgeometry_MIN_METADATA                             0.000844
26_radon_seed_MIN_METADATA                               0.000547
27_wordLevels_MIN_METADATA                               0.000573
299_libras_move_MIN_METADATA                             0.000526
30_personae_MIN_METADATA                                 0.000989
313_spectrometer_MIN_METADATA                            0.000411
31_urbansound_MIN_METADATA                               0.000540


In [97]:
np.percentile(0.2/dgstd['l1'],[0,25,50,75,100])

array([0.00037622, 0.00052519, 0.00067828, 0.00114945, 0.00809511])